In [13]:
%%timeit
import numpy as np
np_array = np.arange(1000000)

The slowest run took 4.81 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 1.97 ms per loop


In [16]:
%%time
np_array +2

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 38.6 µs


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Multi-Dimensional array  Using numpy

In [40]:
A = np.random.randint(1,10,(2,1))
B = np.random.randint(1,12+2,(1,2))
print("A:\n")
print(A)
print("B:\n")
print(B)

A:

[[7]
 [9]]
B:

[[4 8]]


In [42]:
C = A.dot(B)
print(C)

[[28 56]
 [36 72]]


In [43]:
C = B.dot(A)
print(C)

[[100]]


ODD OR EVEN

In [48]:
print(np_array)
np_array % 2 == 0   

[0 1 2 3 4 5 6 7 8 9]


array([ True, False,  True, False,  True, False,  True, False,  True, False], dtype=bool)

In [49]:
np_array[2]

2